name: Build and deploy WAR app to Azure Web App - dnkwebapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11' # Match the Java version in pom.xml
          distribution: 'microsoft'

      - name: Print working directory (Build Job)
        run: pwd

      - name: Build with Maven
        run: mvn clean package

      - name: List target directory (Debugging)
        run: ls -l target

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'target/dnkwebapp.war' # Explicitly specify the .war file

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Print working directory (Deploy Job)
        run: pwd

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List downloaded files (Debugging)
        run: ls -l

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'dnkwebapp'
          slot-name: 'Production'
          package: 'dnkwebapp.war' # Explicitly specify the .war file
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_142B63B47ADA45D9AA5381024910A552 }}
