name: Build and Deploy Java Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: target

      - name: Azure Login (Publish Profile)
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          auth-type: publishprofile

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: techdnkwebapp
          slot-name: devslot
          package: target/techdnkwebapp.war
